# Generated by Django 3.2 on 2023-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaic', '0019_auto_20221123_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvdata',
            name='humidity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pvdata',
            name='open_circuit_voltage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pvdata',
            name='rain',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pvdata',
            name='short_circuit_current',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pvdata',
            name='wind_direction',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pvdata',
            name='wind_speed',
            field=models.FloatField(default=0, null=True),
        ),
    ]
