# Generated by Django 4.2 on 2023-05-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photovoltaic", "0020_auto_20230411_1053"),
    ]

    operations = [
        migrations.RemoveField(model_name="pvdata", name="strings",),
    ]
